### ISSUE TITLE
add .ruby-version to UI

### ISSUE THREAD

**Issue by palladius** [patterns-ai-core/ecommerce-ai-assistant-demo#6]
## Without

```bash
$ rackup
Your Ruby version is 3.2.4, but your Gemfile specified 3.3.4
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/definition.rb:443:in `validate_ruby!'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/definition.rb:418:in `validate_runtime!'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler.rb:157:in `setup'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/setup.rb:13:in `block in <top (required)>'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/ui/shell.rb:159:in `with_level'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/ui/shell.rb:111:in `silence'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/setup.rb:13:in `<top (required)>'
<internal:/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
/Users/ricc/git/ecommerce-ai-assistant-demo/main.rb:3:in `<top (required)>'
/Users/ricc/git/ecommerce-ai-assistant-demo/app.rb:3:in `require_relative'
/Users/ricc/git/ecommerce-ai-assistant-demo/app.rb:3:in `<top (required)>'
<internal:/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
/Users/ricc/git/ecommerce-ai-assistant-demo/config.ru:1:in `block in <main>'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/builder.rb:116:in `eval'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/builder.rb:116:in `new_from_string'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/builder.rb:105:in `load_file'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/builder.rb:66:in `parse_file'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/server.rb:349:in `build_app_and_options_from_config'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/server.rb:249:in `app'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/server.rb:422:in `wrapped_app'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/server.rb:312:in `block in start'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/server.rb:379:in `handle_profiling'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/server.rb:311:in `start'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/lib/rack/server.rb:168:in `start'
/Users/ricc/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rack-2.2.9/bin/rackup:5:in `<top (required)>'
/Users/ricc/.rbenv/versions/3.2.4/bin/rackup:25:in `load'
/Users/ricc/.rbenv/versions/3.2.4/bin/rackup:25:in `<main>'
ricc-macbookpro3:ecommerce-ai-assistant-demo ricc$ 
```

## With

```bash
ricc-macbookpro3:ecommerce-ai-assistant-demo ricc$ cat .ruby-version 
3.3.4
```

then it works.

**Comment by andreibondarev** [comment]
Fixed: https://github.com/patterns-ai-core/ecommerce-ai-assistant-demo/commit/f607e4bba5ecfad469ca217e7f9bf102c54cc018
